environment:
  global:
    HOST: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    CRATE_NAME: remove_dir_all
  matrix:
    # MinGW
    - TARGET: i686-pc-windows-gnu
      HOST: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu
      HOST: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: aarch64-pc-windows-msvc
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # Testing other channels
    # Beta channel
    - TARGET: i686-pc-windows-gnu
      HOST: i686-pc-windows-gnu
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-gnu
      HOST: x86_64-pc-windows-gnu
      RUST_VERSION: beta

    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: aarch64-pc-windows-msvc
      RUST_VERSION: beta
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # Nightly channel
    - TARGET: i686-pc-windows-gnu
      HOST: i686-pc-windows-gnu
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-gnu
      HOST: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: aarch64-pc-windows-msvc
      RUST_VERSION: nightly
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  allow_failures:
    - RUST_VERSION: nightly

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %HOST% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup target install %TARGET%
  - rustc -Vv
  - cargo -V
build_script:
  - cargo build --target %TARGET% &&
    cargo build --target %TARGET% --release
# TODO This is the "test phase", tweak it as you see fit
test_script:
  # we don't run the "test phase" when doing deploys, nor do we run it
  # when the target is aarch64-pc-windows-msvc, since the Appveyor image
  # can't execute that target's executables
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      if not [%TARGET%]==[aarch64-pc-windows-msvc] (
        cargo test --target %TARGET% &&
        cargo test --target %TARGET% --release
      )
    )
