name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [i686, x86_64, aarch64]
        variant: [gnu, msvc]
        channel: [stable, beta, nightly]
        exclude:
          - arch: aarch64
            variant: gnu
    steps:
    - uses: actions/checkout@v2
    - run: rustup default ${{ matrix.channel }}
    - run: rustup target add ${{ matrix.arch }}-pc-windows-${{ matrix.variant }}
    - name: Build
      run: cargo build --verbose --target ${{ matrix.arch }}-pc-windows-${{ matrix.variant }}
    - name: Run tests
      run: cargo test --verbose --target ${{ matrix.arch }}-pc-windows-${{ matrix.variant }}
